# Generated by Django 5.2.9 on 2026-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
