# Generated by Django 5.2.9 on 2026-03-12 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabysitterAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time for availability')),
                ('end_time', models.TimeField(help_text='End time for availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('babysitter', models.ForeignKey(limit_choices_to={'role': 'BABYSITTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Babysitter Availability',
                'verbose_name_plural': 'Babysitter Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('babysitter', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
