# Generated by Django 5.2.9 on 2026-04-05 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_babysitteravailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabysitterStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Story update from babysitter')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the story', null=True, upload_to='stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('babysitter', models.ForeignKey(limit_choices_to={'role': 'BABYSITTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stories_posted', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='parent.babysitterrequest')),
            ],
            options={
                'verbose_name': 'Babysitter Story',
                'verbose_name_plural': 'Babysitter Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
